using System.Reflection;
using EveConsole.Data;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace EveConsole.Services;

/// <summary>How far a copy has got.</summary>
public readonly record struct CopyProgress(
    string Table, int TableIndex, int TableCount, long RowsInTable, long RowsTotal);

/// <summary>
/// Copies every table from one engine into the other, so somebody moving to a server keeps the
/// history they already have.
///
/// <para>Reads through EF and writes through PostgreSQL's binary COPY. Reading through EF is what
/// makes it correct rather than merely fast: SQLite keeps decimals and dates as TEXT, so a raw
/// read hands back strings that would each need parsing back into the type the destination column
/// actually wants. EF's providers already know that mapping in both directions, and having them
/// do it is the difference between a copy that is right and one that is nearly right.</para>
///
/// <para>⚠️ Table order does not matter here, and that is a property of this schema rather than a
/// general truth: it declares no foreign keys, because the relationship between a character and
/// its corporation is enforced in the application. Add one and this needs a topological sort
/// before it will work.</para>
///
/// <para>⚠️ Dates are forced to UTC on the way in. Binary COPY does not pass through the
/// command interceptor that normally does this — nothing here is a DbCommand — and Npgsql
/// rejects any offset but zero.</para>
/// </summary>
public sealed class DatabaseCopyService
{
    /// <summary>Rows read from the source per round trip. Large enough to keep the writer busy,
    /// small enough that one batch of a wide table is not held in memory all at once.</summary>
    private const int BatchSize = 5_000;

    /// <summary>
    /// Copies source into destination. The destination is expected to be empty; this neither
    /// checks nor truncates, because deciding to overwrite somebody's data is the caller's to
    /// make and the UI asks first.
    /// </summary>
    public static async Task<long> CopyAsync(
        Func<AppDbContext> openSource,
        Func<AppDbContext> openDestination,
        string destinationConnectionString,
        IProgress<CopyProgress>? progress,
        CancellationToken ct)
    {
        using var probe = openDestination();
        var tables = probe.Model.GetEntityTypes()
            .Where(e => e.GetTableName() is not null)
            .OrderBy(e => e.GetTableName(), StringComparer.Ordinal)
            .ToList();

        await using var pg = new NpgsqlConnection(destinationConnectionString);
        await pg.OpenAsync(ct);

        long grand = 0;
        var copyOne = typeof(DatabaseCopyService)
            .GetMethod(nameof(CopyTableAsync), BindingFlags.NonPublic | BindingFlags.Static)!;

        for (var i = 0; i < tables.Count; i++)
        {
            ct.ThrowIfCancellationRequested();

            var entity = tables[i];
            var table  = entity.GetTableName()!;

            var task = (Task<long>)copyOne
                .MakeGenericMethod(entity.ClrType)
                .Invoke(null, [openSource, pg, table, progress, i, tables.Count, grand, ct])!;

            var rows = await task;
            grand += rows;

            progress?.Report(new CopyProgress(table, i + 1, tables.Count, rows, grand));
        }

        await ResetIdentitySequencesAsync(pg, ct);
        return grand;
    }

    /// <summary>
    /// Moves every identity sequence past the largest key that was copied.
    ///
    /// <para>⚠️ Without this the copy looks perfect and the first new row fails. An identity
    /// column declared GENERATED BY DEFAULT accepts the explicit ids a copy supplies, but nothing
    /// tells its sequence they were used — it is still at 1, so the next insert that lets the
    /// database choose picks a key that already exists. The failure lands later, on ordinary use,
    /// far from the migration that caused it.</para>
    /// </summary>
    private static async Task ResetIdentitySequencesAsync(NpgsqlConnection pg, CancellationToken ct)
    {
        const string sql = """
            SELECT quote_ident(c.table_name), quote_ident(c.column_name)
            FROM information_schema.columns c
            WHERE c.table_schema = 'public' AND c.is_identity = 'YES'
            """;

        var targets = new List<(string Table, string Column)>();
        await using (var find = new NpgsqlCommand(sql, pg))
        await using (var r = await find.ExecuteReaderAsync(ct))
            while (await r.ReadAsync(ct))
                targets.Add((r.GetString(0), r.GetString(1)));

        foreach (var (table, column) in targets)
        {
            ct.ThrowIfCancellationRequested();

            // setval(..., false) means "the next value is this one", so an empty table is left
            // starting at 1 rather than skipping it.
            var bare = column.Trim('"').Replace("'", "''");
            var bump = $"""
                SELECT setval(
                    pg_get_serial_sequence('public.{table}', '{bare}'),
                    COALESCE((SELECT MAX({column}) FROM public.{table}), 0) + 1,
                    false)
                """;

            await using var cmd = new NpgsqlCommand(bump, pg);
            await cmd.ExecuteNonQueryAsync(ct);
        }
    }

    private static async Task<long> CopyTableAsync<T>(
        Func<AppDbContext> openSource,
        NpgsqlConnection pg,
        string table,
        IProgress<CopyProgress>? progress,
        int index,
        int total,
        long runningTotal,
        CancellationToken ct) where T : class
    {
        using var src = openSource();
        src.ChangeTracker.AutoDetectChangesEnabled = false;

        var entity = src.Model.FindEntityType(typeof(T))!;

        // Only real, readable columns. A shadow property has no PropertyInfo to read from, and
        // this model has none; if one appears it must be handled rather than silently skipped.
        // Paired with the converter EF would use for each one. A property's CLR type is not
        // always what the column holds: an enum is stored as an int, and any property with a
        // value converter is stored as whatever that converter produces.
        var props = entity.GetProperties()
            .Where(p => p.PropertyInfo is not null)
            .Select(p => (Property: p, Converter: p.GetTypeMapping().Converter))
            .ToList();

        var columns = string.Join(", ", props.Select(p => $"\"{p.Property.GetColumnName()}\""));
        var copySql = $"COPY \"{table}\" ({columns}) FROM STDIN (FORMAT BINARY)";

        long written = 0;
        var  offset  = 0;

        // ⚠️ An ordered page, because Skip/Take without one is not guaranteed to be a stable
        // window: rows could be repeated or missed between batches. The primary key is the
        // cheapest ordering that exists on every table.
        var key = entity.FindPrimaryKey()?.Properties.Select(p => p.Name).ToList() ?? [];

        await using var writer = await pg.BeginBinaryImportAsync(copySql, ct);

        while (true)
        {
            ct.ThrowIfCancellationRequested();

            IQueryable<T> query = src.Set<T>().AsNoTracking();
            foreach (var (name, n) in key.Select((k, n) => (k, n)))
                query = n == 0
                    ? ((IQueryable<T>)query).OrderBy(e => EF.Property<object>(e, name))
                    : ((IOrderedQueryable<T>)query).ThenBy(e => EF.Property<object>(e, name));

            var batch = await query.Skip(offset).Take(BatchSize).ToListAsync(ct);
            if (batch.Count == 0) break;

            foreach (var row in batch)
            {
                await writer.StartRowAsync(ct);
                foreach (var (property, converter) in props)
                {
                    var value = property.PropertyInfo!.GetValue(row);

                    // ⚠️ Through EF's own converter, not straight from the property. Writing
                    // the CLR value directly failed on the first enum it met — "Writing values
                    // of 'AlarmActionKind' is not supported for parameters having no NpgsqlDbType"
                    // — because the column holds an int and the property does not. Asking EF
                    // what the provider value is covers enums and every other converted type at
                    // once, rather than special-casing them one failure at a time.
                    if (converter is not null) value = converter.ConvertToProvider(value);

                    // See the class remarks: COPY bypasses the interceptor, so UTC is enforced here.
                    value = value switch
                    {
                        DateTimeOffset dto when dto.Offset != TimeSpan.Zero => dto.ToUniversalTime(),
                        DateTime dt when dt.Kind == DateTimeKind.Local      => dt.ToUniversalTime(),
                        DateTime dt when dt.Kind == DateTimeKind.Unspecified
                            => DateTime.SpecifyKind(dt, DateTimeKind.Utc),
                        _ => value,
                    };

                    // ⚠️ A belt for the braces above: an enum with no explicit converter still
                    // reaches here as an enum, and Npgsql cannot infer a type for it. Unboxing to
                    // the underlying integral type is what the column expects anyway.
                    if (value is Enum boxed)
                        value = Convert.ChangeType(boxed, Enum.GetUnderlyingType(boxed.GetType()));

                    if (value is null) await writer.WriteNullAsync(ct);
                    else               await writer.WriteAsync(value, ct);
                }
                written++;
            }

            offset += batch.Count;
            src.ChangeTracker.Clear();

            progress?.Report(new CopyProgress(table, index, total, written, runningTotal + written));

            if (batch.Count < BatchSize) break;
        }

        await writer.CompleteAsync(ct);
        return written;
    }
}
