using Microsoft.EntityFrameworkCore;

namespace EveConsole.Data;

/// <summary>
/// Everything a PostgreSQL database needs beyond what <c>EnsureCreated</c> builds from the model.
///
/// <para>The SQLite path in App.axaml.cs is nearly 2,400 lines, and almost none of it applies
/// here. Of its 158 <c>CREATE TABLE</c> statements, 156 duplicate an entity EF has already
/// created — they are dead code on any fresh database, and its 116 <c>ALTER TABLE</c> patches
/// exist to carry old SQLite files forward. A server created today starts at the current schema
/// and has no history to catch up on.</para>
///
/// <para>⚠️ It could not simply be run anyway: 47 of those statements use <c>AUTOINCREMENT</c>,
/// which PostgreSQL rejects at parse time even under <c>IF NOT EXISTS</c>, so a table already
/// present would still fail. What remains below is the part that is genuinely load-bearing.</para>
///
/// <para>⚠️ This file and the SQLite block have to be kept in step by hand: a new index or seed
/// row added there and not here works for every existing user and silently does not exist for
/// Postgres ones. <c>tools/PgSchemaCheck</c> compares the two index lists and fails on drift,
/// which covers the case that is easiest to forget.</para>
/// </summary>
public static class PostgresSchema
{
    /// <param name="includeSeeds">
    /// ⚠️ False when the database is about to receive a copy of an existing one. The seeds
    /// write fixed primary keys — MarketPricingConfigs 1 and 2, AlertSettings 1 — and the
    /// copy then carries the same keys across, so seeding first turns the migration into a
    /// duplicate-key failure partway through. The rows arrive with the data instead, and the
    /// next ordinary start seeds anything genuinely absent, every seed being written to no-op
    /// when its table is already populated.
    /// </param>
    public static void Apply(
        AppDbContext db,
        IProgress<(double Pct, string Status)>? progress = null,
        bool includeSeeds = true)
    {
        progress?.Report((30, "Preparing database…"));
        foreach (var sql in Tables)  db.Database.ExecuteSqlRaw(sql);

        progress?.Report((55, "Building indexes…"));
        foreach (var sql in Indexes) db.Database.ExecuteSqlRaw(sql);

        if (!includeSeeds) return;

        progress?.Report((75, "Writing defaults…"));
        foreach (var sql in Seeds)   db.Database.ExecuteSqlRaw(sql);
    }

    /// <summary>
    /// Tables <c>EnsureCreated</c> will not add.
    ///
    /// <para>It builds a schema only into an empty database, so anything introduced after a
    /// database first existed has to be spelled out here. Two of these are not entities at all —
    /// single-row settings the UI writes directly with ADO, which the model has never known
    /// about. The third is an ordinary entity that simply arrived later, and needs saying for
    /// exactly the same reason.</para>
    /// </summary>
    private static readonly string[] Tables =
    [
        // A staged alarm's acknowledgements: this character's episode is quiet until then. An
        // entity, but one that arrived after databases existed — EnsureCreated will not add it.
        """
        CREATE TABLE IF NOT EXISTS "AlarmSnoozes" (
            "AlarmId"  BIGINT      NOT NULL,
            "ScopeKey" TEXT        NOT NULL,
            "Episode"  TEXT        NOT NULL DEFAULT '',
            "Until"    TIMESTAMPTZ NOT NULL,
            PRIMARY KEY ("AlarmId", "ScopeKey")
        )
        """,
        // The store web channel: what the app has told a site about each order, and everything
        // a site has sent back. Entities that arrived after databases existed.
        """
        CREATE TABLE IF NOT EXISTS "StoreWebPushes" (
            "StoreId" INTEGER NOT NULL,
            "OrderId" INTEGER NOT NULL,
            "Hash"    TEXT    NOT NULL DEFAULT '',
            PRIMARY KEY ("StoreId", "OrderId")
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "StoreWebEvents" (
            "Id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "StoreId"    INTEGER     NOT NULL DEFAULT 0,
            "Seq"        BIGINT      NOT NULL DEFAULT 0,
            "Kind"       TEXT        NOT NULL DEFAULT '',
            "WebOrderId" TEXT        NOT NULL DEFAULT '',
            "BuyerId"    BIGINT      NOT NULL DEFAULT 0,
            "BuyerName"  TEXT        NOT NULL DEFAULT '',
            "Payload"    TEXT        NOT NULL DEFAULT '',
            "ReceivedAt" TIMESTAMPTZ NOT NULL,
            "Outcome"    TEXT        NOT NULL DEFAULT '',
            "Detail"     TEXT        NOT NULL DEFAULT '',
            "OrderRef"   TEXT        NOT NULL DEFAULT ''
        )
        """,
        // Discord's named webhooks. An entity that arrived after databases existed.
        """
        CREATE TABLE IF NOT EXISTS "DiscordWebhooks" (
            "Id"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" TEXT    NOT NULL DEFAULT '',
            "Url"  TEXT    NOT NULL DEFAULT ''
        )
        """,
        // Pictures the site shows for a store: the banner, bytes and all.
        """
        CREATE TABLE IF NOT EXISTS "StoreWebAssets" (
            "StoreId"     INTEGER     NOT NULL,
            "Kind"        TEXT        NOT NULL DEFAULT 'banner',
            "ContentType" TEXT        NOT NULL DEFAULT '',
            "Sha256"      TEXT        NOT NULL DEFAULT '',
            "FileName"    TEXT        NOT NULL DEFAULT '',
            "Width"       INTEGER     NOT NULL DEFAULT 0,
            "Height"      INTEGER     NOT NULL DEFAULT 0,
            "Bytes"       BYTEA       NOT NULL,
            "UpdatedAt"   TIMESTAMPTZ NOT NULL,
            PRIMARY KEY ("StoreId", "Kind")
        )
        """,
        // The NPC corporation facts the SDE import drops, fetched from ESI when a page is opened.
        // ⚠️ DOUBLE PRECISION for the tax rate: REAL is float4 on PostgreSQL and would round it.
        // Map and station fields the import was leaving in the file.
        """
        ALTER TABLE "SdeConstellations" ADD COLUMN IF NOT EXISTS "WormholeClassId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeRegions" ADD COLUMN IF NOT EXISTS "Description" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "SdeRegions" ADD COLUMN IF NOT EXISTS "NebulaId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeRegions" ADD COLUMN IF NOT EXISTS "WormholeClassId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeSolarSystems" ADD COLUMN IF NOT EXISTS "WormholeClassId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeSolarSystems" ADD COLUMN IF NOT EXISTS "Border" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "SdeSolarSystems" ADD COLUMN IF NOT EXISTS "Corridor" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "SdeSolarSystems" ADD COLUMN IF NOT EXISTS "Fringe" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "SdeSolarSystems" ADD COLUMN IF NOT EXISTS "Hub" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "SdeSolarSystems" ADD COLUMN IF NOT EXISTS "International" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "SdeSolarSystems" ADD COLUMN IF NOT EXISTS "Regional" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "SdeSolarSystems" ADD COLUMN IF NOT EXISTS "Luminosity" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeSolarSystems" ADD COLUMN IF NOT EXISTS "VisualEffect" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "SdeSolarSystems" ADD COLUMN IF NOT EXISTS "StarId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeStationOperations" ADD COLUMN IF NOT EXISTS "ActivityId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeStationOperations" ADD COLUMN IF NOT EXISTS "Description" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "SdeStationOperations" ADD COLUMN IF NOT EXISTS "ManufacturingFactor" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeStationOperations" ADD COLUMN IF NOT EXISTS "ResearchFactor" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeStationOperations" ADD COLUMN IF NOT EXISTS "Ratio" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeStationOperations" ADD COLUMN IF NOT EXISTS "Border" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeStationOperations" ADD COLUMN IF NOT EXISTS "Corridor" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeStationOperations" ADD COLUMN IF NOT EXISTS "Fringe" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeStationOperations" ADD COLUMN IF NOT EXISTS "Hub" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeStations" ADD COLUMN IF NOT EXISTS "CelestialIndex" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeStations" ADD COLUMN IF NOT EXISTS "OrbitId" BIGINT NULL
        """,
        """
        ALTER TABLE "SdeStations" ADD COLUMN IF NOT EXISTS "OrbitIndex" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeStations" ADD COLUMN IF NOT EXISTS "ReprocessingHangarFlag" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeStations" ADD COLUMN IF NOT EXISTS "UseOperationName" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "SdeStations" ADD COLUMN IF NOT EXISTS "X" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeStations" ADD COLUMN IF NOT EXISTS "Y" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeStations" ADD COLUMN IF NOT EXISTS "Z" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,

        // Fields the SDE has always carried that the import did not read.
        // ⚠️ Additive only, and every NOT NULL carries a DEFAULT: an older build inserting
        // without naming these columns has to go on working against the same database.
        """
        ALTER TABLE "SdeCategories" ADD COLUMN IF NOT EXISTS "IconId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeDogmaAttributes" ADD COLUMN IF NOT EXISTS "Description" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "SdeDogmaAttributes" ADD COLUMN IF NOT EXISTS "IconId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeDogmaAttributes" ADD COLUMN IF NOT EXISTS "MinAttributeId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeDogmaAttributes" ADD COLUMN IF NOT EXISTS "MaxAttributeId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeDogmaAttributes" ADD COLUMN IF NOT EXISTS "TooltipTitle" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "SdeDogmaAttributes" ADD COLUMN IF NOT EXISTS "TooltipDescription" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "SdeDogmaAttributes" ADD COLUMN IF NOT EXISTS "DataType" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeDogmaAttributes" ADD COLUMN IF NOT EXISTS "DisplayWhenZero" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "SdeDogmaAttributes" ADD COLUMN IF NOT EXISTS "ChargeRechargeTimeId" INTEGER NULL
        """,

        // What the fitting engine runs on: each effect's category and the attributes that hold
        // its cycle time, cap use, range and resistance, and its modifierInfo as rows. Mirrored
        // for SQLite in SdeImportService.EnsureSdeSchema.
        """
        ALTER TABLE "SdeDogmaEffects" ADD COLUMN IF NOT EXISTS "EffectCategory" INTEGER NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeDogmaEffects" ADD COLUMN IF NOT EXISTS "IsWarpSafe" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "SdeDogmaEffects" ADD COLUMN IF NOT EXISTS "DisallowAutoRepeat" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "SdeDogmaEffects" ADD COLUMN IF NOT EXISTS "DurationAttributeId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeDogmaEffects" ADD COLUMN IF NOT EXISTS "DischargeAttributeId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeDogmaEffects" ADD COLUMN IF NOT EXISTS "RangeAttributeId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeDogmaEffects" ADD COLUMN IF NOT EXISTS "FalloffAttributeId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeDogmaEffects" ADD COLUMN IF NOT EXISTS "TrackingSpeedAttributeId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeDogmaEffects" ADD COLUMN IF NOT EXISTS "ResistanceAttributeId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeDogmaEffects" ADD COLUMN IF NOT EXISTS "FittingUsageChanceAttributeId" INTEGER NULL
        """,
        """
        CREATE TABLE IF NOT EXISTS "SdeFighterAbilities" (
            "AbilityId"         INTEGER          NOT NULL,
            "Name"              TEXT             NOT NULL DEFAULT '',
            "Tooltip"           TEXT             NOT NULL DEFAULT '',
            "TargetMode"        TEXT             NOT NULL DEFAULT '',
            "IconId"            INTEGER          NULL,
            "DisallowInHighSec" BOOLEAN          NOT NULL DEFAULT FALSE,
            "DisallowInLowSec"  BOOLEAN          NOT NULL DEFAULT FALSE,
            CONSTRAINT "PK_SdeFighterAbilities" PRIMARY KEY ("AbilityId")
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "SdeFighterTypeAbilities" (
            "TypeId"          INTEGER          NOT NULL,
            "Slot"            INTEGER          NOT NULL,
            "AbilityId"       INTEGER          NOT NULL,
            "CooldownSeconds" DOUBLE PRECISION NULL,
            "ChargeCount"     INTEGER          NULL,
            "RearmSeconds"    DOUBLE PRECISION NULL,
            CONSTRAINT "PK_SdeFighterTypeAbilities" PRIMARY KEY ("TypeId", "Slot")
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "SdeDbuffs" (
            "DbuffId"       INTEGER NOT NULL,
            "Name"          TEXT    NOT NULL DEFAULT '',
            "AggregateMode" TEXT    NOT NULL DEFAULT '',
            "Operation"     TEXT    NOT NULL DEFAULT '',
            "ShowInUi"      TEXT    NOT NULL DEFAULT '',
            CONSTRAINT "PK_SdeDbuffs" PRIMARY KEY ("DbuffId")
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "SdeDbuffModifiers" (
            "DbuffId"     INTEGER NOT NULL,
            "Ordinal"     INTEGER NOT NULL,
            "Kind"        TEXT    NOT NULL DEFAULT '',
            "AttributeId" INTEGER NOT NULL,
            "GroupId"     INTEGER NULL,
            "SkillTypeId" INTEGER NULL,
            CONSTRAINT "PK_SdeDbuffModifiers" PRIMARY KEY ("DbuffId", "Ordinal")
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "SdeDogmaEffectModifiers" (
            "EffectId"             INTEGER NOT NULL,
            "Ordinal"              INTEGER NOT NULL,
            "Func"                 TEXT    NOT NULL,
            "Domain"               TEXT    NOT NULL,
            "Operation"            INTEGER NULL,
            "ModifiedAttributeId"  INTEGER NULL,
            "ModifyingAttributeId" INTEGER NULL,
            "GroupId"              INTEGER NULL,
            "SkillTypeId"          INTEGER NULL,
            "StoppedEffectId"      INTEGER NULL,
            CONSTRAINT "PK_SdeDogmaEffectModifiers" PRIMARY KEY ("EffectId", "Ordinal")
        )
        """,
        """
        ALTER TABLE "SdeFactions" ADD COLUMN IF NOT EXISTS "IconId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeFactions" ADD COLUMN IF NOT EXISTS "ShortDescription" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "SdeFactions" ADD COLUMN IF NOT EXISTS "SizeFactor" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeFactions" ADD COLUMN IF NOT EXISTS "UniqueName" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "SdeGroups" ADD COLUMN IF NOT EXISTS "IconId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeGroups" ADD COLUMN IF NOT EXISTS "FittableNonSingleton" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "SdeGroups" ADD COLUMN IF NOT EXISTS "UseBasePrice" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "SdeMetaGroups" ADD COLUMN IF NOT EXISTS "Description" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "SdeMetaGroups" ADD COLUMN IF NOT EXISTS "IconId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeMetaGroups" ADD COLUMN IF NOT EXISTS "IconSuffix" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "SdeMetaGroups" ADD COLUMN IF NOT EXISTS "ColorHex" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "SdeRaces" ADD COLUMN IF NOT EXISTS "IconId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeRaces" ADD COLUMN IF NOT EXISTS "ShipTypeId" INTEGER NULL
        """,

        // Where each structure and rig industry bonus actually comes from, which the app has been
        // inferring from rig description text instead.
        """
        CREATE TABLE IF NOT EXISTS "SdeIndustryModifierSources" (
            "TypeId"           INTEGER NOT NULL,
            "Activity"         TEXT    NOT NULL,
            "BonusKind"        TEXT    NOT NULL,
            "DogmaAttributeId" INTEGER NOT NULL,
            "FilterId"         INTEGER NULL,
            PRIMARY KEY ("TypeId", "Activity", "BonusKind", "DogmaAttributeId")
        )
        """,

        // The SDE's names in the client's other languages, for display; the English stays in every
        // Name column. See SdeName. The key columns carry no default, as in the other tables made
        // here: no build older than this one writes to the table, and a row without its key is a
        // bug to be refused, not filled in. Mirrored for SQLite in SdeImportService.EnsureSdeSchema.
        """
        CREATE TABLE IF NOT EXISTS "SdeNames" (
            "Kind" INTEGER NOT NULL,
            "Id"   BIGINT  NOT NULL,
            "Lang" TEXT    NOT NULL,
            "Name" TEXT    NOT NULL DEFAULT '',
            CONSTRAINT "PK_SdeNames" PRIMARY KEY ("Kind", "Id", "Lang")
        )
        """,
        // Its descriptions, in a table of their own because they are never loaded whole: read a
        // row at a time, by the key. See SdeText. The same shape and the same rules as SdeNames.
        // Mirrored for SQLite in SdeImportService.EnsureSdeSchema.
        """
        CREATE TABLE IF NOT EXISTS "SdeTexts" (
            "Kind" INTEGER NOT NULL,
            "Id"   BIGINT  NOT NULL,
            "Lang" TEXT    NOT NULL,
            "Text" TEXT    NOT NULL DEFAULT '',
            CONSTRAINT "PK_SdeTexts" PRIMARY KEY ("Kind", "Id", "Lang")
        )
        """,

        // ⚠️ PackagedVolume above all: haul volumes were computed from the ASSEMBLED
        // figure, which is 115,000 against 10,000 for a Vexor.
        """
        ALTER TABLE "SdeTypes" ADD COLUMN IF NOT EXISTS "PackagedVolume" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeTypes" ADD COLUMN IF NOT EXISTS "MetaLevel" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeTypes" ADD COLUMN IF NOT EXISTS "TechLevel" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeTypes" ADD COLUMN IF NOT EXISTS "IsRepackable" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "SdeTypes" ADD COLUMN IF NOT EXISTS "IsDynamicType" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "SdeTypes" ADD COLUMN IF NOT EXISTS "Radius" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeTypes" ADD COLUMN IF NOT EXISTS "VariationParentTypeId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeTypes" ADD COLUMN IF NOT EXISTS "SoundId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeTypes" ADD COLUMN IF NOT EXISTS "ShipTreeGroupId" INTEGER NULL
        """,

        // npcCorporations.yaml has thirty-two fields; the import read three. These are the rest
        // of the ones worth having, and every existing database needs them added by hand.
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "StationId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "SolarSystemId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "Ticker" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "Description" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "CeoId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "TaxRate" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "Size" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "Extent" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "MemberLimit" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "MinSecurity" DOUBLE PRECISION NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "MinimumJoinStanding" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "EnemyId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "FriendId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "RaceId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "IconId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "MainActivityId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "SecondaryActivityId" INTEGER NULL
        """,
        """
        ALTER TABLE "SdeNpcCorporations" ADD COLUMN IF NOT EXISTS "Deleted" BOOLEAN NOT NULL DEFAULT FALSE
        """,

        """
        CREATE TABLE IF NOT EXISTS "EsiNpcCorpProfiles" (
            "CorporationId" BIGINT PRIMARY KEY,
            "Ticker"        TEXT             NOT NULL DEFAULT '',
            "Description"   TEXT             NOT NULL DEFAULT '',
            "Url"           TEXT             NOT NULL DEFAULT '',
            "CeoId"         BIGINT           NOT NULL DEFAULT 0,
            "HomeStationId" BIGINT           NOT NULL DEFAULT 0,
            "MemberCount"   INTEGER          NOT NULL DEFAULT 0,
            "TaxRate"       DOUBLE PRECISION NOT NULL DEFAULT 0,
            "FetchedUtc"    TIMESTAMPTZ      NOT NULL DEFAULT NOW()
        )
        """,

        """
        CREATE TABLE IF NOT EXISTS "TradeOpportunitiesSettings" (
            "Id"                     INTEGER NOT NULL PRIMARY KEY,
            "ExcludedMarketGroupIds" TEXT    NOT NULL DEFAULT ''
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "IndustryOpportunitiesSettings" (
            "Id"                     INTEGER NOT NULL PRIMARY KEY,
            "ExcludedMarketGroupIds" TEXT    NOT NULL DEFAULT ''
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "BackgroundWorkerStatus" (
            "Id"            INTEGER     NOT NULL PRIMARY KEY,
            "Version"       TEXT        NOT NULL DEFAULT '',
            "HostName"      TEXT        NOT NULL DEFAULT '',
            "ProcessId"     INTEGER     NOT NULL DEFAULT 0,
            "Headless"      BOOLEAN     NOT NULL DEFAULT FALSE,
            "LeaseTakenUtc" TIMESTAMPTZ NOT NULL DEFAULT now(),
            "HeartbeatUtc"  TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "WorkerActivity" (
            "Key"        TEXT        NOT NULL PRIMARY KEY,
            "Status"     TEXT        NOT NULL DEFAULT '',
            "Running"    BOOLEAN     NOT NULL DEFAULT FALSE,
            "LastRunUtc" TIMESTAMPTZ NULL,
            "NextRunUtc" TIMESTAMPTZ NULL,
            "Count"      INTEGER     NULL,
            "UpdatedUtc" TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """,
        // Count arrived after the table did, within this same unreleased branch — so a database
        // that already has the table needs it added rather than created.
        """
        ALTER TABLE "WorkerActivity" ADD COLUMN IF NOT EXISTS "Count" INTEGER NULL
        """,

        // ⚠️ AppErrorLog is built by EnsureCreated from the model, which only builds into an EMPTY
        // database — so every install that already exists needs these two added by hand. They say
        // which client wrote a row, which stopped being obvious the moment several of them began
        // sharing one log.
        //
        // ⚠️ NOT NULL with a default rather than nullable: a client still on an older build inserts
        // without naming these columns at all, and the default is what lets that go on working.
        """
        ALTER TABLE "AppErrorLog" ADD COLUMN IF NOT EXISTS "HostName" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "AppErrorLog" ADD COLUMN IF NOT EXISTS "Headless" BOOLEAN NOT NULL DEFAULT FALSE
        """,

        // Packaged-only arrived after InvLevelGroups did.
        """
        ALTER TABLE "InvLevelGroups" ADD COLUMN IF NOT EXISTS "PackagedOnly" BOOLEAN NOT NULL DEFAULT FALSE
        """,

        // Where an asset's root location IS, filled by AssetLocations on every asset poll. Null
        // until the first poll after this upgrade, and for the few roots nothing can resolve —
        // nullable rather than defaulted so that null keeps meaning "unknown". An older build
        // inserting without naming them goes on working, which is the whole of the constraint.
        """
        ALTER TABLE "EsiAssets" ADD COLUMN IF NOT EXISTS "SolarSystemId" INTEGER NULL
        """,
        """
        ALTER TABLE "EsiAssets" ADD COLUMN IF NOT EXISTS "RegionId" INTEGER NULL
        """,

        // An alert that arrived after databases existed. NOT NULL with a default, so an older
        // build's seed, which does not name it, still inserts.
        """
        ALTER TABLE "AlertSettings" ADD COLUMN IF NOT EXISTS "IndustryJobsReady" BOOLEAN NOT NULL DEFAULT TRUE
        """,
        """
        ALTER TABLE "AlertSettings" ADD COLUMN IF NOT EXISTS "OutstandingContracts" BOOLEAN NOT NULL DEFAULT TRUE
        """,
        """
        ALTER TABLE "AlertSettings" ADD COLUMN IF NOT EXISTS "ExpiringContracts" BOOLEAN NOT NULL DEFAULT TRUE
        """,
        // The Planetary Industry alerts. Mirrored for SQLite in App.axaml.cs.
        """
        ALTER TABLE "AlertSettings" ADD COLUMN IF NOT EXISTS "PiExtractors" BOOLEAN NOT NULL DEFAULT TRUE
        """,
        """
        ALTER TABLE "AlertSettings" ADD COLUMN IF NOT EXISTS "PiStorage" BOOLEAN NOT NULL DEFAULT TRUE
        """,
        """
        ALTER TABLE "AlertSettings" ADD COLUMN IF NOT EXISTS "PiInputs" BOOLEAN NOT NULL DEFAULT TRUE
        """,
        """
        ALTER TABLE "AlertSettings" ADD COLUMN IF NOT EXISTS "PiFreeSlots" BOOLEAN NOT NULL DEFAULT TRUE
        """,
        """
        ALTER TABLE "AlertSettings" ADD COLUMN IF NOT EXISTS "PiStaleData" BOOLEAN NOT NULL DEFAULT TRUE
        """,

        // The HTTP status ESI answered a contract's item pull with, and the repair it makes
        // possible: corporation contracts issued by another corporation were once marked pulled
        // without a call, on a belief the data contradicted. Marked, no items, no answer
        // recorded — those go back to the sweep. No-ops once every such row has an answer.
        // Mirrored for SQLite in App.axaml.cs.
        """
        ALTER TABLE "EsiContracts" ADD COLUMN IF NOT EXISTS "ItemsStatus" INTEGER NOT NULL DEFAULT 0
        """,
        """
        UPDATE "EsiContracts" SET "ItemsPulled" = FALSE
        WHERE "OwnerType" = 'corporation' AND "IssuerCorporationId" <> "OwnerId"
          AND "ItemsPulled" AND "ItemsStatus" = 0
          AND "Type" IN ('item_exchange', 'auction', 'courier')
          AND NOT EXISTS (SELECT 1 FROM "EsiContractItems" i WHERE i."ContractId" = "EsiContracts"."ContractId")
        """,

        // When a contract was last seen in the status it has since left — what dates a deletion,
        // which ESI does not; see ContractLag. Nullable, so an older build inserting without
        // naming it goes on working. Mirrored for SQLite in App.axaml.cs.
        """
        ALTER TABLE "EsiContracts" ADD COLUMN IF NOT EXISTS "StatusChangedAfter" TIMESTAMPTZ NULL
        """,

        // A corporation whose token could not read project contributors had the whole
        // corp.projects poll written into its denied list by an earlier build, which stopped its
        // projects updating. Contributors are denied under their own key now; the projects key
        // comes back out. No-op once no list holds it. Mirrored for SQLite in App.axaml.cs.
        """
        UPDATE "Corporations" SET "DeniedEndpoints" = btrim(replace(',' || "DeniedEndpoints" || ',', ',corp.projects,', ','), ',')
        WHERE ',' || "DeniedEndpoints" || ',' LIKE '%,corp.projects,%'
        """,

        // The hours an alarm is on; null means always. Older builds neither read nor write them.
        """
        ALTER TABLE "Alarms" ADD COLUMN IF NOT EXISTS "ActiveFrom" TEXT NULL
        """,
        """
        ALTER TABLE "Alarms" ADD COLUMN IF NOT EXISTS "ActiveThru" TEXT NULL
        """,

        // The last undock the location poll saw, for the Ship Undocks alarm. Null until a
        // character next undocks; an older build never writes them and never needs to.
        """
        ALTER TABLE "CharacterStatuses" ADD COLUMN IF NOT EXISTS "UndockedAt" TIMESTAMPTZ NULL
        """,
        """
        ALTER TABLE "CharacterStatuses" ADD COLUMN IF NOT EXISTS "UndockedFromId" BIGINT NULL
        """,
        """
        ALTER TABLE "CharacterStatuses" ADD COLUMN IF NOT EXISTS "UndockedSystemId" INTEGER NULL
        """,
        """
        ALTER TABLE "CharacterStatuses" ADD COLUMN IF NOT EXISTS "UndockedShipTypeId" INTEGER NULL
        """,
        """
        ALTER TABLE "CharacterStatuses" ADD COLUMN IF NOT EXISTS "UndockedShipItemId" BIGINT NULL
        """,
        """
        ALTER TABLE "CharacterStatuses" ADD COLUMN IF NOT EXISTS "UndockedShipName" TEXT NULL
        """,
        """
        ALTER TABLE "CharacterStatuses" ADD COLUMN IF NOT EXISTS "SystemChangedAt" TIMESTAMPTZ NULL
        """,
        """
        ALTER TABLE "CharacterStatuses" ADD COLUMN IF NOT EXISTS "PreviousSystemId" INTEGER NULL
        """,

        // The store's web channel. Every column has a default, so an older build's rows and
        // reads are untouched.
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebEnabled" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebUrl" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebSecret" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebTheme" TEXT NOT NULL DEFAULT 'dark'
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebBuyerMaySwitch" BOOLEAN NOT NULL DEFAULT TRUE
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebThemes" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebMailUpdates" BOOLEAN NOT NULL DEFAULT TRUE
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebPollMinutes" INTEGER NOT NULL DEFAULT 5
        """,
        // A type's daily price snapshot gained its reprocessing value.
        """
        ALTER TABLE "TypePriceSnapshots" ADD COLUMN IF NOT EXISTS "ReprocessValue" DOUBLE PRECISION
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebBlurb" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebCursor" BIGINT NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebGeneration" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebSiteVersion" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebLastSyncAt" TIMESTAMPTZ NULL
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebLastError" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebCloudflareAccountId" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebWorkerName" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebCustomHostname" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebEveClientId" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "WebEveClientSecret" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "LimitEnabled" BOOLEAN NOT NULL DEFAULT FALSE
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "LimitUnits" INTEGER NOT NULL DEFAULT 1
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "LimitScope" TEXT NOT NULL DEFAULT 'type'
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "LimitPeriod" TEXT NOT NULL DEFAULT 'all'
        """,
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "LimitPeriodCount" INTEGER NOT NULL DEFAULT 1
        """,
        // The language the shop speaks to buyers; empty for the app's own.
        """
        ALTER TABLE "Stores" ADD COLUMN IF NOT EXISTS "Language" TEXT NOT NULL DEFAULT ''
        """,



        """
        ALTER TABLE "TrackedOrders" ADD COLUMN IF NOT EXISTS "WebOrderId" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "TrackedOrders" ADD COLUMN IF NOT EXISTS "MailUpdates" BOOLEAN NOT NULL DEFAULT TRUE
        """,
        // An order delivered over several contracts: each with the units it carries, and how many
        // of the order have been accepted and how many are waiting on the buyer.
        """
        ALTER TABLE "TrackedOrders" ADD COLUMN IF NOT EXISTS "LinkedContracts" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "TrackedOrders" ADD COLUMN IF NOT EXISTS "UnitsDelivered" INTEGER NOT NULL DEFAULT 0
        """,
        """
        ALTER TABLE "TrackedOrders" ADD COLUMN IF NOT EXISTS "UnitsContracted" INTEGER NOT NULL DEFAULT 0
        """,


        // ── Agent telemetry ──────────────────────────────────────────────────
        //
        // ⚠️ BIGSERIAL, not AUTOINCREMENT: PostgreSQL rejects the SQLite spelling at parse time
        // even under IF NOT EXISTS. BOOLEAN, not INTEGER. And BIGINT for the unit counts —
        // deliberately not REAL, which is float4 here and has silently truncated numbers in this
        // codebase before.
        //
        // The SQLite spelling of these three is in AgentTelemetrySchema; keep the two in step.
        """
        CREATE TABLE IF NOT EXISTS "AgentInteractions" (
            "Id"             BIGSERIAL   PRIMARY KEY,
            "ConversationId" TEXT        NOT NULL DEFAULT '',
            "StartedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
            "DurationMs"     INTEGER     NOT NULL DEFAULT 0,
            "Provider"       TEXT        NOT NULL DEFAULT '',
            "Model"          TEXT        NOT NULL DEFAULT '',
            "RoundTrips"     INTEGER     NOT NULL DEFAULT 0,
            "ToolCallCount"  INTEGER     NOT NULL DEFAULT 0,
            "QueryCount"     INTEGER     NOT NULL DEFAULT 0,
            "ToolsUsed"      TEXT        NOT NULL DEFAULT '',
            "StopReason"     TEXT        NOT NULL DEFAULT '',
            "Error"          TEXT        NOT NULL DEFAULT '',
            "UserChars"      INTEGER     NOT NULL DEFAULT 0,
            "ResponseChars"  INTEGER     NOT NULL DEFAULT 0
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "AgentToolCalls" (
            "Id"            BIGSERIAL   PRIMARY KEY,
            "InteractionId" BIGINT      NOT NULL DEFAULT 0,
            "Sequence"      INTEGER     NOT NULL DEFAULT 0,
            "OccurredAt"    TIMESTAMPTZ NOT NULL DEFAULT now(),
            "ToolName"      TEXT        NOT NULL DEFAULT '',
            "DurationMs"    INTEGER     NOT NULL DEFAULT 0,
            "InputJson"     TEXT        NOT NULL DEFAULT '',
            "ResultChars"   INTEGER     NOT NULL DEFAULT 0,
            "RowCount"      INTEGER     NOT NULL DEFAULT -1,
            "Error"         TEXT        NOT NULL DEFAULT ''
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "ServiceUsage" (
            "Id"                BIGSERIAL   PRIMARY KEY,
            "OccurredAt"        TIMESTAMPTZ NOT NULL DEFAULT now(),
            "InteractionId"     BIGINT      NULL,
            "Kind"              TEXT        NOT NULL DEFAULT '',
            "Provider"          TEXT        NOT NULL DEFAULT '',
            "Model"             TEXT        NOT NULL DEFAULT '',
            "IsLocal"           BOOLEAN     NOT NULL DEFAULT FALSE,
            "UnitKind"          TEXT        NOT NULL DEFAULT '',
            "InputUnits"        BIGINT      NOT NULL DEFAULT 0,
            "OutputUnits"       BIGINT      NOT NULL DEFAULT 0,
            "CacheReadUnits"    BIGINT      NOT NULL DEFAULT 0,
            "CacheWriteUnits"   BIGINT      NOT NULL DEFAULT 0,
            "UnitsAreEstimated" BOOLEAN     NOT NULL DEFAULT FALSE,
            "DurationMs"        INTEGER     NOT NULL DEFAULT 0,
            "Error"             TEXT        NOT NULL DEFAULT ''
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "ServiceRates" (
            "Id"                BIGSERIAL      PRIMARY KEY,
            "Kind"              TEXT           NOT NULL DEFAULT '',
            "Provider"          TEXT           NOT NULL DEFAULT '',
            "Model"             TEXT           NOT NULL DEFAULT '',
            "InputPerUnit"      NUMERIC(18,10) NOT NULL DEFAULT 0,
            "OutputPerUnit"     NUMERIC(18,10) NOT NULL DEFAULT 0,
            "CacheReadPerUnit"  NUMERIC(18,10) NOT NULL DEFAULT 0,
            "CacheWritePerUnit" NUMERIC(18,10) NOT NULL DEFAULT 0,
            "Notes"             TEXT           NOT NULL DEFAULT '',
            "UpdatedAt"         TIMESTAMPTZ    NOT NULL DEFAULT now()
        )
        """,

        // Why the SSO refused an owner's refresh token; "" while it is good. Mirrored for SQLite
        // in App.axaml.cs.
        """
        ALTER TABLE "Characters" ADD COLUMN IF NOT EXISTS "TokenError" TEXT NOT NULL DEFAULT ''
        """,
        """
        ALTER TABLE "Corporations" ADD COLUMN IF NOT EXISTS "TokenError" TEXT NOT NULL DEFAULT ''
        """,

        // Fits saved in the fitting tool, as EFT text. Mirrored for SQLite in App.axaml.cs.
        """
        CREATE TABLE IF NOT EXISTS "SavedFits" (
            "Id"         BIGSERIAL   PRIMARY KEY,
            "Name"       TEXT        NOT NULL DEFAULT '',
            "ShipTypeId" INTEGER     NOT NULL DEFAULT 0,
            "Eft"        TEXT        NOT NULL DEFAULT '',
            "State"      TEXT        NOT NULL DEFAULT '',
            "UpdatedAt"  TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """,
        """
        ALTER TABLE "SavedFits" ADD COLUMN IF NOT EXISTS "State" TEXT NOT NULL DEFAULT ''
        """,

        // ── Corp moon-mining ledger, one row per day ─────────────────────────
        //
        // Replaces "EsiCorpMiningLedger", which was keyed without the date and so held only each
        // miner's newest day per ore — see CorpMiningLedgerEntry. The old rows move across once
        // and the old table goes. Each date is put back at 00:00 UTC: the old reader stored ESI's
        // bare date as midnight in the polling machine's zone, and rounding to the NEAREST
        // midnight undoes that on either side of UTC, where truncating would not east of it.
        // Mirrored for SQLite in App.axaml.cs.
        """
        CREATE TABLE IF NOT EXISTS "EsiCorpMiningLedgerDays" (
            "CorporationId"         BIGINT      NOT NULL,
            "ObserverId"            BIGINT      NOT NULL,
            "LastUpdated"           TIMESTAMPTZ NOT NULL,
            "CharacterId"           BIGINT      NOT NULL,
            "RecordedCorporationId" BIGINT      NOT NULL,
            "TypeId"                INTEGER     NOT NULL,
            "Quantity"              BIGINT      NOT NULL,
            CONSTRAINT "PK_EsiCorpMiningLedgerDays" PRIMARY KEY
                ("CorporationId", "ObserverId", "LastUpdated", "CharacterId", "RecordedCorporationId", "TypeId")
        )
        """,
        """
        DO $$
        BEGIN
            IF to_regclass('"EsiCorpMiningLedger"') IS NOT NULL THEN
                INSERT INTO "EsiCorpMiningLedgerDays"
                    ("CorporationId", "ObserverId", "LastUpdated", "CharacterId",
                     "RecordedCorporationId", "TypeId", "Quantity")
                SELECT "CorporationId", "ObserverId",
                       date_trunc('day', ("LastUpdated" AT TIME ZONE 'UTC') + interval '12 hours')
                           AT TIME ZONE 'UTC',
                       "CharacterId", "RecordedCorporationId", "TypeId", "Quantity"
                FROM "EsiCorpMiningLedger"
                ON CONFLICT DO NOTHING;
                DROP TABLE "EsiCorpMiningLedger";
            END IF;
        END $$
        """,

        // ── Jump bridges entered by hand ─────────────────────────────────────
        //
        // An entity that arrived after databases existed. Mirrored for SQLite in App.axaml.cs.
        """
        CREATE TABLE IF NOT EXISTS "ManualJumpBridges" (
            "Id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "FromSystemId" INTEGER     NOT NULL DEFAULT 0,
            "ToSystemId"   INTEGER     NOT NULL DEFAULT 0,
            "Note"         TEXT        NOT NULL DEFAULT '',
            "CreatedAt"    TIMESTAMPTZ NOT NULL
        )
        """,

        // ── Hoboleaks build info ─────────────────────────────────────────────
        //
        // Revision arrived after PostgreSQL support and reached servers only through the Hobo
        // import's own ALTER, spelled for SQLite: INTEGER, which is int4 here where the model has
        // a long. Added as the model has it, and an int4 one widened once.
        """
        ALTER TABLE "HoboBuildInfos" ADD COLUMN IF NOT EXISTS "Revision" BIGINT NOT NULL DEFAULT 0
        """,
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.columns
                       WHERE table_schema = current_schema() AND table_name = 'HoboBuildInfos'
                         AND column_name = 'Revision' AND data_type = 'integer') THEN
                ALTER TABLE "HoboBuildInfos" ALTER COLUMN "Revision" TYPE BIGINT;
            END IF;
        END $$
        """,

        // ── Planetary Industry ───────────────────────────────────────────────
        //
        // The PI box on Settings → Characters. Default TRUE, so every character already listed
        // keeps doing PI until somebody clears it. Mirrored for SQLite in App.axaml.cs.
        """
        ALTER TABLE "WorklistIndyChars" ADD COLUMN IF NOT EXISTS "PlanetaryIndustry" BOOLEAN NOT NULL DEFAULT TRUE
        """,
        // Colony layouts, one colony replaced whole at a time, and what tax learning works from.
        // Entities that arrived after databases existed. Mirrored for SQLite in App.axaml.cs.
        // ⚠️ DOUBLE PRECISION, never REAL: REAL is float4 here and would round a tax rate.
        """
        CREATE TABLE IF NOT EXISTS "EsiPlanetaryLayouts" (
            "CharacterId" BIGINT      NOT NULL,
            "PlanetId"    INTEGER     NOT NULL,
            "LastUpdate"  TIMESTAMPTZ NOT NULL,
            "FetchedAt"   TIMESTAMPTZ NOT NULL,
            CONSTRAINT "PK_EsiPlanetaryLayouts" PRIMARY KEY ("CharacterId", "PlanetId")
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "EsiPlanetaryPins" (
            "CharacterId"            BIGINT           NOT NULL,
            "PlanetId"               INTEGER          NOT NULL,
            "PinId"                  BIGINT           NOT NULL,
            "TypeId"                 INTEGER          NOT NULL DEFAULT 0,
            "SchematicId"            INTEGER          NULL,
            "InstallTime"            TIMESTAMPTZ      NULL,
            "ExpiryTime"             TIMESTAMPTZ      NULL,
            "LastCycleStart"         TIMESTAMPTZ      NULL,
            "Latitude"               DOUBLE PRECISION NOT NULL DEFAULT 0,
            "Longitude"              DOUBLE PRECISION NOT NULL DEFAULT 0,
            "ExtractorProductTypeId" INTEGER          NULL,
            "ExtractorCycleTime"     INTEGER          NULL,
            "ExtractorQtyPerCycle"   INTEGER          NULL,
            "ExtractorHeadRadius"    DOUBLE PRECISION NULL,
            "ExtractorHeadCount"     INTEGER          NOT NULL DEFAULT 0,
            CONSTRAINT "PK_EsiPlanetaryPins" PRIMARY KEY ("CharacterId", "PlanetId", "PinId")
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "EsiPlanetaryPinContents" (
            "CharacterId" BIGINT  NOT NULL,
            "PlanetId"    INTEGER NOT NULL,
            "PinId"       BIGINT  NOT NULL,
            "TypeId"      INTEGER NOT NULL,
            "Amount"      BIGINT  NOT NULL DEFAULT 0,
            CONSTRAINT "PK_EsiPlanetaryPinContents" PRIMARY KEY ("CharacterId", "PlanetId", "PinId", "TypeId")
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "EsiPlanetaryRoutes" (
            "CharacterId"      BIGINT           NOT NULL,
            "PlanetId"         INTEGER          NOT NULL,
            "RouteId"          BIGINT           NOT NULL,
            "SourcePinId"      BIGINT           NOT NULL DEFAULT 0,
            "DestinationPinId" BIGINT           NOT NULL DEFAULT 0,
            "ContentTypeId"    INTEGER          NOT NULL DEFAULT 0,
            "Quantity"         DOUBLE PRECISION NOT NULL DEFAULT 0,
            "Waypoints"        TEXT             NOT NULL DEFAULT '',
            CONSTRAINT "PK_EsiPlanetaryRoutes" PRIMARY KEY ("CharacterId", "PlanetId", "RouteId")
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "EsiPlanetaryLinks" (
            "CharacterId"      BIGINT  NOT NULL,
            "PlanetId"         INTEGER NOT NULL,
            "SourcePinId"      BIGINT  NOT NULL,
            "DestinationPinId" BIGINT  NOT NULL,
            "LinkLevel"        INTEGER NOT NULL DEFAULT 0,
            CONSTRAINT "PK_EsiPlanetaryLinks" PRIMARY KEY ("CharacterId", "PlanetId", "SourcePinId", "DestinationPinId")
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "PiColonyMovements" (
            "Id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "CharacterId" BIGINT      NOT NULL DEFAULT 0,
            "PlanetId"    INTEGER     NOT NULL DEFAULT 0,
            "FromUpdate"  TIMESTAMPTZ NOT NULL,
            "ToUpdate"    TIMESTAMPTZ NOT NULL,
            "TypeId"      INTEGER     NOT NULL DEFAULT 0,
            "Removed"     BIGINT      NOT NULL DEFAULT 0,
            "Added"       BIGINT      NOT NULL DEFAULT 0
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "PiPlanetTaxRates" (
            "PlanetId"    INTEGER          NOT NULL PRIMARY KEY,
            "Rate"        DOUBLE PRECISION NOT NULL DEFAULT 0,
            "LearnedAt"   TIMESTAMPTZ      NOT NULL,
            "JournalId"   BIGINT           NOT NULL DEFAULT 0,
            "CharacterId" BIGINT           NOT NULL DEFAULT 0,
            "Source"      TEXT             NOT NULL DEFAULT '',
            "Units"       BIGINT           NOT NULL DEFAULT 0
        )
        """,
        // The SDE's PI additions: which processors run each schematic, and the raw resources each
        // planet type yields. New tables, so the schema fingerprint grows and the SDE import that
        // fills them starts on its own after the upgrade. Mirrored for SQLite in
        // SdeImportService.EnsureSdeSchema.
        """
        CREATE TABLE IF NOT EXISTS "SdePlanetSchematicPins" (
            "SchematicId" INTEGER NOT NULL,
            "PinTypeId"   INTEGER NOT NULL,
            CONSTRAINT "PK_SdePlanetSchematicPins" PRIMARY KEY ("SchematicId", "PinTypeId")
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "SdePlanetTypeResources" (
            "PlanetTypeId"   INTEGER NOT NULL,
            "ResourceTypeId" INTEGER NOT NULL,
            "PlanetType"     TEXT    NOT NULL DEFAULT '',
            CONSTRAINT "PK_SdePlanetTypeResources" PRIMARY KEY ("PlanetTypeId", "ResourceTypeId")
        )
        """,
    ];

    /// <summary>
    /// Every index the app creates by hand. Copied verbatim from the SQLite block — the syntax is
    /// identical in both engines — and all of them are listed rather than only the 27 the model
    /// lacks, because <c>IF NOT EXISTS</c> makes the overlap free and a short list would need
    /// re-deriving each time the model changes.
    ///
    /// <para>⚠️ These are not optional decoration. <c>IX_KillMailAttackers_Corp</c> is the
    /// difference between a corporation's Kills tab taking 1.7 seconds and taking over ten
    /// minutes; a Postgres install without it would look broken rather than slow.</para>
    ///
    /// <para>Public so the drift check can read the list rather than parse this file.</para>
    /// </summary>
    public static readonly string[] Indexes =
    [
        // ⚠️ Here, not beside its table in Tables: the drift check reads this list, and an index
        // anywhere else is invisible to it — this one was reported missing while it existed.
        """CREATE INDEX IF NOT EXISTS "IX_StoreWebEvents_Store_Seq" ON "StoreWebEvents" ("StoreId", "Seq")""",
        """CREATE UNIQUE INDEX IF NOT EXISTS "IX_ManualJumpBridges_Pair" ON "ManualJumpBridges" ("FromSystemId", "ToSystemId")""",
        """CREATE INDEX IF NOT EXISTS "IX_OrderLabels_Label" ON "OrderLabels" ("Label")""",
        """CREATE INDEX IF NOT EXISTS "IX_SaleLabels_Label" ON "SaleLabels" ("Label")""",
        """CREATE INDEX IF NOT EXISTS "IX_StoreMails_In" ON "StoreMails" ("StoreId", "MailId", "Direction")""",
        """CREATE INDEX IF NOT EXISTS "IX_StoreMails_Store_At" ON "StoreMails" ("StoreId", "At")""",
        """CREATE INDEX IF NOT EXISTS "IX_EsiLpStoreOffers_Type" ON "EsiLpStoreOffers" ("TypeId")""",
        """CREATE UNIQUE INDEX IF NOT EXISTS "IX_EsiCorpMemberSessions_Key" ON "EsiCorpMemberSessions" ("CorporationId", "CharacterId", "LogonDate")""",
        """CREATE INDEX IF NOT EXISTS "IX_SdeCelestials_System" ON "SdeCelestials" ("SolarSystemId")""",
        """CREATE INDEX IF NOT EXISTS "IX_MarketRawOrders_TypeId" ON "MarketRawOrders" ("ConfigId", "TypeId", "IsBuyOrder")""",
        """CREATE UNIQUE INDEX IF NOT EXISTS "IX_StandingBuyOrders_TypeId_LocationId" ON "StandingBuyOrders" ("TypeId", "LocationId")""",
        """CREATE UNIQUE INDEX IF NOT EXISTS "IX_WorklistMarketAlts_LocationId" ON "WorklistMarketAlts" ("LocationId")""",
        """CREATE UNIQUE INDEX IF NOT EXISTS "IX_WorklistIndyChars_CharacterId" ON "WorklistIndyChars" ("CharacterId")""",
        """CREATE UNIQUE INDEX IF NOT EXISTS "IX_WorklistCorpAlts_CorporationId" ON "WorklistCorpAlts" ("CorporationId")""",
        """CREATE UNIQUE INDEX IF NOT EXISTS "IX_WorklistStationLevels_GroupId_LocationId" ON "WorklistStationLevels" ("GroupId", "LocationId")""",
        """CREATE UNIQUE INDEX IF NOT EXISTS "IX_WorklistIndyScopeStations_LocationId" ON "WorklistIndyScopeStations" ("LocationId")""",
        """CREATE UNIQUE INDEX IF NOT EXISTS "IX_GameLogEvents_SourceFile_LineNumber" ON "GameLogEvents" ("SourceFile", "LineNumber")""",
        """CREATE INDEX IF NOT EXISTS "IX_GameLogEvents_OccurredAt" ON "GameLogEvents" ("OccurredAt")""",
        """CREATE INDEX IF NOT EXISTS "IX_GameLogEvents_CharacterId_Kind" ON "GameLogEvents" ("CharacterId", "Kind")""",
        """CREATE UNIQUE INDEX IF NOT EXISTS "IX_ChatMessages_SourceFile_LineNumber" ON "ChatMessages" ("SourceFile", "LineNumber")""",
        """CREATE INDEX IF NOT EXISTS "IX_ChatMessages_OccurredAt" ON "ChatMessages" ("OccurredAt")""",
        """CREATE INDEX IF NOT EXISTS "IX_ChatMessages_ChannelName_OccurredAt" ON "ChatMessages" ("ChannelName", "OccurredAt")""",
        """CREATE INDEX IF NOT EXISTS "IX_KillMailDetails_KillMailTime" ON "KillMailDetails" ("KillMailTime")""",
        """CREATE INDEX IF NOT EXISTS "IX_KillMailAttackers_KillMailId" ON "KillMailAttackers" ("KillMailId")""",
        """CREATE INDEX IF NOT EXISTS "IX_KillMailItems_KillMailId" ON "KillMailItems" ("KillMailId")""",
        """CREATE INDEX IF NOT EXISTS "IX_KillMailAttackers_Corp" ON "KillMailAttackers" ("CorporationId", "KillMailId", "CharacterId")""",
        """CREATE INDEX IF NOT EXISTS "IX_KillMailAttackers_Alliance" ON "KillMailAttackers" ("AllianceId", "KillMailId", "CorporationId")""",
        """CREATE UNIQUE INDEX IF NOT EXISTS "IX_StructureFittings_Slot" ON "StructureFittings" ("StructureId","Band","SlotIndex")""",
        """CREATE INDEX IF NOT EXISTS "IX_IndyStructureServices_StructureId" ON "IndyStructureServices" ("StructureId")""",
        """CREATE INDEX IF NOT EXISTS "IX_KillMailAttackers_CharacterId" ON "KillMailAttackers" ("CharacterId", "KillMailId")""",
        """CREATE INDEX IF NOT EXISTS "IX_MapSystemJumps_Bucket" ON "MapSystemJumps" ("Bucket")""",
        """CREATE INDEX IF NOT EXISTS "IX_MapSystemKills_Bucket" ON "MapSystemKills" ("Bucket")""",
        """CREATE INDEX IF NOT EXISTS "IX_MapSystemDailies_Day" ON "MapSystemDailies" ("Day")""",
        """CREATE INDEX IF NOT EXISTS "IX_MapSovereignties_Bucket" ON "MapSovereignties" ("Bucket")""",
        """CREATE INDEX IF NOT EXISTS "IX_MapSovStructures_SystemId" ON "MapSovStructures" ("SystemId")""",
        """CREATE INDEX IF NOT EXISTS "IX_KillMailDetails_SolarSystemId" ON "KillMailDetails" ("SolarSystemId")""",
        """CREATE INDEX IF NOT EXISTS "IX_EsiStructureNames_SolarSystemId" ON "EsiStructureNames" ("SolarSystemId")""",
        """CREATE INDEX IF NOT EXISTS "IX_SdeAgents_Location" ON "SdeAgents" ("LocationId")""",
        """CREATE UNIQUE INDEX IF NOT EXISTS "IX_IntelReports_ChatMessageId" ON "IntelReports" ("ChatMessageId")""",
        """CREATE INDEX IF NOT EXISTS "IX_IntelReports_System_Time" ON "IntelReports" ("SystemId", "ReportedAt")""",
        """CREATE INDEX IF NOT EXISTS "IX_IntelReports_Obsolete_Time" ON "IntelReports" ("Obsolete", "ReportedAt")""",
        """CREATE INDEX IF NOT EXISTS "IX_IntelReportCharacters_CharacterId" ON "IntelReportCharacters" ("CharacterId")""",
        """CREATE INDEX IF NOT EXISTS "IX_Alarms_Enabled" ON "Alarms" ("Enabled")""",
        """CREATE INDEX IF NOT EXISTS "IX_SavedFits_ShipTypeId" ON "SavedFits" ("ShipTypeId")""",
        """CREATE INDEX IF NOT EXISTS "IX_AlarmActions_AlarmId" ON "AlarmActions" ("AlarmId")""",
        """CREATE INDEX IF NOT EXISTS "IX_AlarmSeenKeys_Alarm_Seen" ON "AlarmSeenKeys" ("AlarmId", "FirstSeenAt")""",
        """CREATE INDEX IF NOT EXISTS "IX_AlarmEvents_Alarm_Fired" ON "AlarmEvents" ("AlarmId", "FiredAt")""",
        """CREATE INDEX IF NOT EXISTS "IX_AlarmAlerts_Dismissed_Created" ON "AlarmAlerts" ("Dismissed", "CreatedAt")""",

        // Agent telemetry. Same list as AgentTelemetrySchema.Indexes — keep the two in step.
        """CREATE INDEX IF NOT EXISTS "IX_AgentInteractions_StartedAt" ON "AgentInteractions" ("StartedAt")""",
        """CREATE INDEX IF NOT EXISTS "IX_AgentInteractions_Conversation" ON "AgentInteractions" ("ConversationId", "StartedAt")""",
        """CREATE INDEX IF NOT EXISTS "IX_AgentToolCalls_Interaction" ON "AgentToolCalls" ("InteractionId", "Sequence")""",
        """CREATE INDEX IF NOT EXISTS "IX_AgentToolCalls_OccurredAt" ON "AgentToolCalls" ("OccurredAt")""",
        """CREATE INDEX IF NOT EXISTS "IX_ServiceUsage_OccurredAt" ON "ServiceUsage" ("OccurredAt")""",
        """CREATE INDEX IF NOT EXISTS "IX_ServiceUsage_Kind_OccurredAt" ON "ServiceUsage" ("Kind", "OccurredAt")""",
        """CREATE UNIQUE INDEX IF NOT EXISTS "IX_ServiceRates_Key" ON "ServiceRates" ("Kind", "Provider", "Model")""",

        // EF's own names for indexes created above under these. The model uses these names now
        // (HasDatabaseName), so the copies exist only where EF built the database before it did —
        // a fresh install got each index twice. Dropping one loses nothing: the index it copies
        // stays under the other name. Mirrored for SQLite in App.axaml.cs.
        """DROP INDEX IF EXISTS "IX_AgentInteractions_ConversationId_StartedAt" """,
        """DROP INDEX IF EXISTS "IX_AgentToolCalls_InteractionId_Sequence" """,
        """DROP INDEX IF EXISTS "IX_AlarmAlerts_Dismissed_CreatedAt" """,
        """DROP INDEX IF EXISTS "IX_AlarmEvents_AlarmId_FiredAt" """,
        """DROP INDEX IF EXISTS "IX_AlarmSeenKeys_AlarmId_FirstSeenAt" """,
        """DROP INDEX IF EXISTS "IX_EsiCorpMemberSessions_CorporationId_CharacterId_LogonDate" """,
        """DROP INDEX IF EXISTS "IX_IntelReports_Obsolete_ReportedAt" """,
        """DROP INDEX IF EXISTS "IX_IntelReports_SystemId_ReportedAt" """,
        """DROP INDEX IF EXISTS "IX_MarketRawOrders_ConfigId_TypeId_IsBuyOrder" """,
        """DROP INDEX IF EXISTS "IX_SdeAgents_LocationId" """,
        """DROP INDEX IF EXISTS "IX_SdeCelestials_SolarSystemId" """,
        """DROP INDEX IF EXISTS "IX_ServiceRates_Kind_Provider_Model" """,
        """DROP INDEX IF EXISTS "IX_StoreWebEvents_StoreId_Seq" """,
        """DROP INDEX IF EXISTS "IX_StructureFittings_StructureId_Band_SlotIndex" """,
    ];

    /// <summary>
    /// The rows a new install cannot start without: a market to price against, the settings row
    /// every preferences screen reads, and the two opportunity filters.
    ///
    /// <para>⚠️ Every <c>1</c> and <c>0</c> from the SQLite originals that lands in a bool column
    /// is written <c>true</c>/<c>false</c> here. SQLite stores a bool as INTEGER and accepts
    /// either; PostgreSQL maps it to <c>boolean</c> and rejects the integer outright. Same reason
    /// <c>INSERT OR IGNORE</c> becomes <c>ON CONFLICT DO NOTHING</c> — the SQLite spelling is not
    /// SQL PostgreSQL will parse.</para>
    ///
    /// <para>The <c>WHERE NOT EXISTS</c> forms are left exactly as they are: they are already
    /// portable, and they mean "seed only an empty table", which is not the same thing as
    /// per-row conflict handling and must not be rewritten into it.</para>
    ///
    /// <para>⚠️ <c>NULL::bigint</c>, not a bare <c>NULL</c>. In an <c>INSERT … SELECT … UNION
    /// ALL</c> PostgreSQL settles the union's column types before it ever looks at the target,
    /// and an untyped NULL settles as <c>text</c> — so the insert fails with "column
    /// StationFilter is of type bigint but expression is of type text". SQLite is dynamically
    /// typed and never had an opinion. This was caught by applying the file to a real server;
    /// no amount of reading it would have shown it.</para>
    /// </summary>
    private static readonly string[] Seeds =
    [
        """
        INSERT INTO "PriceHistoryRegions" ("RegionId", "RegionName")
        SELECT 10000002, 'The Forge' WHERE NOT EXISTS (SELECT 1 FROM "PriceHistoryRegions")
        UNION ALL
        SELECT 10000043, 'Domain'    WHERE NOT EXISTS (SELECT 1 FROM "PriceHistoryRegions")
        """,
        """
        INSERT INTO "MarketPricingConfigs"
            ("Method", "LocationName", "LocationId", "PriceType", "IsEnabled", "SortOrder", "LastStatus", "StationFilter", "UsePercentileFilter", "PercentilePercent")
        SELECT 'Region', 'The Forge', 10000002, 'Midpoint', true, 0, '', NULL::bigint, true, 1.0
        WHERE NOT EXISTS (SELECT 1 FROM "MarketPricingConfigs")
        UNION ALL
        SELECT 'Region', 'Domain',    10000043, 'Midpoint', true, 1, '', NULL::bigint, true, 1.0
        WHERE NOT EXISTS (SELECT 1 FROM "MarketPricingConfigs")
        """,
        """
        INSERT INTO "MarketDefaultSettings"
            ("Id", "AssetValueConfigId", "AssetValuePriceType", "ManufacturingConfigId", "ManufacturingPriceType",
             "MissingPriceMarkupPct", "FilterLowballBuyOrders", "LowballBuyOrderThresholdPct",
             "PurchaseWhenCheaper", "PurchaseThresholdPct")
        SELECT 1,
               (SELECT "Id" FROM "MarketPricingConfigs" WHERE "LocationId" = 10000002 LIMIT 1), 'Sell',
               (SELECT "Id" FROM "MarketPricingConfigs" WHERE "LocationId" = 10000002 LIMIT 1), 'Sell',
               15.0, true, 10.0,
               false, 100.0
        WHERE NOT EXISTS (SELECT 1 FROM "MarketDefaultSettings")
        """,
        """
        INSERT INTO "AlertSettings"
            ("Id", "SkillQueueEmpty", "SkillQueuePaused", "SkillQueueEmptyInDays", "SkillQueueEmptyDays",
             "AssetSafety", "InactiveStandingProjects", "StandingBuyOrdersAttention", "UnriggedIndustryJobs", "IndustryJobsReady",
             "OutstandingContracts", "ExpiringContracts",
             "PiExtractors", "PiStorage", "PiInputs", "PiFreeSlots", "PiStaleData")
        VALUES (1, true, true, true, 30, true, true, true, true, true, true, true, true, true, true, true, true)
        ON CONFLICT DO NOTHING
        """,
        """
        INSERT INTO "TradeOpportunitiesSettings" ("Id", "ExcludedMarketGroupIds")
        VALUES (1, '2,1954,1659,1396,150,19')
        ON CONFLICT DO NOTHING
        """,
        """
        INSERT INTO "IndustryOpportunitiesSettings" ("Id", "ExcludedMarketGroupIds")
        VALUES (1, '')
        ON CONFLICT DO NOTHING
        """,
    ];
}
